const responseObj = {
    "" : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    hi : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    Hi : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    HI : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    hii : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    Hii : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    hello : "Hey! How are you doing ?",
    Hello : "Hey! How are you doing ?",
    HELLO : "Hey! How are you doing ?",
    good : "nice..!",
    Good : "nice..!",
    hey : "Hey! What's Up",
    Hey : "Hey! What's Up",
    today : new Date().toDateString(),
    Today : new Date().toDateString(),
    time : new Date().toLocaleTimeString(),
    Time : new Date().toLocaleTimeString(),
    appoinment : "Click \" Download Appoinment Letter \" at Bottom ↓ to download your Appoinment Letter.",
    Appoinment : "Click \" Download Appoinment Letter \" at Bottom ↓ to download your Appoinment Letter.",
    help : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    Help : "Hi, How can i help you ?  --  Head , Shoulder , Eye , Heart , Lung , Stomach & Legs etc.   ( choose what you want ! )",
    etc : " Neck , Teeth , Ear , Hair , Blood Pressure / Hypertension.",
    Etc : " Neck , Teeth , Ear , Hair , Blood Pressure / Hypertension.",

    Head : "Headache itself is a painful and disabling feature of a small number of primary headache disorders, namely migraine, tension-type headache, and cluster headache. Headache can also be caused by or occur secondarily to a long list of other conditions, the most common of which is medication-overuse headache",
    head : "Headache itself is a painful and disabling feature of a small number of primary headache disorders, namely migraine, tension-type headache, and cluster headache. Headache can also be caused by or occur secondarily to a long list of other conditions, the most common of which is medication-overuse headache",

    Shoulder : "Shoulder pain is very common and causes substantial morbidity. Standardised classification systems based upon presumed patho-anatomical origins have proved poorly reproducible and hampered epidemiological research. Despite this, there is evidence that exposure to combinations of physical workplace strains such as overhead working, heavy lifting and forceful work as well as working in an awkward posture increase the risk of shoulder disorders.",
    shoulder : "Shoulder pain is very common and causes substantial morbidity. Standardised classification systems based upon presumed patho-anatomical origins have proved poorly reproducible and hampered epidemiological research. Despite this, there is evidence that exposure to combinations of physical workplace strains such as overhead working, heavy lifting and forceful work as well as working in an awkward posture increase the risk of shoulder disorders.",

    eye : "Knowledge of common eye diseases is generally lacking. Age-related macular degeneration is the leading cause of blindness in Australia, yet only 20% of the present study population had heard of it. As there are often no early symptoms for glaucoma, community awareness of this disease and the need for screening of people at risk may allow timely diagnosis and more effective therapy before advanced visual field loss has occurred. An informed public is more likely to present earlier with visual symptoms before irreversible visual loss has occurred and is more likely to comply better with recommended therapy.",
    Eye : "Knowledge of common eye diseases is generally lacking. Age-related macular degeneration is the leading cause of blindness in Australia, yet only 20% of the present study population had heard of it. As there are often no early symptoms for glaucoma, community awareness of this disease and the need for screening of people at risk may allow timely diagnosis and more effective therapy before advanced visual field loss has occurred. An informed public is more likely to present earlier with visual symptoms before irreversible visual loss has occurred and is more likely to comply better with recommended therapy.",

    Heart : "Cardiac patients demonstrated relatively adequate knowledge of heart attack warning symptoms. These patients also demonstrated adequate awareness of proper actions during cardiovascular emergencies. However, respondents were not aware of the most important risk factors for cardiovascular disease. Knowledge of stroke symptoms was also extremely poor. Socioeconomic status, and personal history of heart attack and stroke were positively correlated with good knowledge. Future patient education efforts should address the awareness of the important cardiovascular risk factors and knowledge of cardiovascular warning symptoms.",
    heart : "Cardiac patients demonstrated relatively adequate knowledge of heart attack warning symptoms. These patients also demonstrated adequate awareness of proper actions during cardiovascular emergencies. However, respondents were not aware of the most important risk factors for cardiovascular disease. Knowledge of stroke symptoms was also extremely poor. Socioeconomic status, and personal history of heart attack and stroke were positively correlated with good knowledge. Future patient education efforts should address the awareness of the important cardiovascular risk factors and knowledge of cardiovascular warning symptoms.",

    Lungs : "Lung disease refers to several types of diseases or disorders that prevent the lungs from functioning properly. Lung disease can affect respiratory function, or the ability to breathe, and pulmonary function, which is how well lungs work. There are many different lung diseases, some of which are caused by bacterial, viral, or fungal infections. Other lung diseases are associated with environmental factors, including asthma, mesothelioma, and lung cancer.",
    lungs : "Lung disease refers to several types of diseases or disorders that prevent the lungs from functioning properly. Lung disease can affect respiratory function, or the ability to breathe, and pulmonary function, which is how well lungs work. There are many different lung diseases, some of which are caused by bacterial, viral, or fungal infections. Other lung diseases are associated with environmental factors, including asthma, mesothelioma, and lung cancer.",
    Lung : "Lung disease refers to several types of diseases or disorders that prevent the lungs from functioning properly. Lung disease can affect respiratory function, or the ability to breathe, and pulmonary function, which is how well lungs work. There are many different lung diseases, some of which are caused by bacterial, viral, or fungal infections. Other lung diseases are associated with environmental factors, including asthma, mesothelioma, and lung cancer.",
    lung : "Lung disease refers to several types of diseases or disorders that prevent the lungs from functioning properly. Lung disease can affect respiratory function, or the ability to breathe, and pulmonary function, which is how well lungs work. There are many different lung diseases, some of which are caused by bacterial, viral, or fungal infections. Other lung diseases are associated with environmental factors, including asthma, mesothelioma, and lung cancer.",

    Stomach : "People may experience stomach issues for several reasons. These can be as common as poor eating habits. In some cases, however, stomach issues may be due to common digestive disorders. Disturbances to this process can cause a range of symptoms, from cramps to vomiting. Many of these issues may pass with time and pose little risk of complication. However, seemingly common stomach issues can be the result of several digestive disorders. Knowing the signs and symptoms of common digestive disorders can help people identify them and seek relevant treatment.",
    stomach : "People may experience stomach issues for several reasons. These can be as common as poor eating habits. In some cases, however, stomach issues may be due to common digestive disorders. Disturbances to this process can cause a range of symptoms, from cramps to vomiting. Many of these issues may pass with time and pose little risk of complication. However, seemingly common stomach issues can be the result of several digestive disorders. Knowing the signs and symptoms of common digestive disorders can help people identify them and seek relevant treatment.",

    Legs : "There are many types of vascular diseases that can occur in the legs - below are some of the common ones that can be treated at the Center for Vascular Medicine and the cause of the disease. You can generalize these diseases as failures to transport blood to or from key areas of the body. It is best to treat these diseases as early as possible to avoid future complications. There are some medications that can be prescribed to modulate factors that affect the vascular system. These include cholesterol medications, blood pressure medications, and blood thinners.",
    legs : "There are many types of vascular diseases that can occur in the legs - below are some of the common ones that can be treated at the Center for Vascular Medicine and the cause of the disease. You can generalize these diseases as failures to transport blood to or from key areas of the body. It is best to treat these diseases as early as possible to avoid future complications. There are some medications that can be prescribed to modulate factors that affect the vascular system. These include cholesterol medications, blood pressure medications, and blood thinners.",
    Leg : "There are many types of vascular diseases that can occur in the legs - below are some of the common ones that can be treated at the Center for Vascular Medicine and the cause of the disease. You can generalize these diseases as failures to transport blood to or from key areas of the body. It is best to treat these diseases as early as possible to avoid future complications. There are some medications that can be prescribed to modulate factors that affect the vascular system. These include cholesterol medications, blood pressure medications, and blood thinners.",
    leg : "There are many types of vascular diseases that can occur in the legs - below are some of the common ones that can be treated at the Center for Vascular Medicine and the cause of the disease. You can generalize these diseases as failures to transport blood to or from key areas of the body. It is best to treat these diseases as early as possible to avoid future complications. There are some medications that can be prescribed to modulate factors that affect the vascular system. These include cholesterol medications, blood pressure medications, and blood thinners.",

    Neck : "Neck pain is common. Poor posture — whether from leaning over a computer or hunching over a workbench — strains neck muscles. Osteoarthritis also is a common cause of neck pain. Rarely, neck pain can be a symptom of a more serious problem. Seek medical care for neck pain with numbness or loss of strength in the arms or hands or for pain that shoots into a shoulder or down an arm.",
    neck : "Neck pain is common. Poor posture — whether from leaning over a computer or hunching over a workbench — strains neck muscles. Osteoarthritis also is a common cause of neck pain. Rarely, neck pain can be a symptom of a more serious problem. Seek medical care for neck pain with numbness or loss of strength in the arms or hands or for pain that shoots into a shoulder or down an arm.",

    Teeth : "Most oral health conditions are largely preventable and can be treated in their early stages. Most cases are dental caries (tooth decay), periodontal diseases, tooth loss and oral cancers. Other oral conditions of public health importance are orofacial clefts, noma (severe gangrenous disease starting in the mouth mostly affecting children) and oro-dental trauma. The WHO Global Oral Health Status Report (2022) estimated that oral diseases affect close to 3.5 billion people worldwide, with 3 out of 4 people affected living in middle-income countries. Globally, an estimated 2 billion people suffer from caries of permanent teeth and 514 million children suffer from caries of primary teeth. ",
    teeth : "Most oral health conditions are largely preventable and can be treated in their early stages. Most cases are dental caries (tooth decay), periodontal diseases, tooth loss and oral cancers. Other oral conditions of public health importance are orofacial clefts, noma (severe gangrenous disease starting in the mouth mostly affecting children) and oro-dental trauma. The WHO Global Oral Health Status Report (2022) estimated that oral diseases affect close to 3.5 billion people worldwide, with 3 out of 4 people affected living in middle-income countries. Globally, an estimated 2 billion people suffer from caries of permanent teeth and 514 million children suffer from caries of primary teeth. ",
    Tooth : "Most oral health conditions are largely preventable and can be treated in their early stages. Most cases are dental caries (tooth decay), periodontal diseases, tooth loss and oral cancers. Other oral conditions of public health importance are orofacial clefts, noma (severe gangrenous disease starting in the mouth mostly affecting children) and oro-dental trauma. The WHO Global Oral Health Status Report (2022) estimated that oral diseases affect close to 3.5 billion people worldwide, with 3 out of 4 people affected living in middle-income countries. Globally, an estimated 2 billion people suffer from caries of permanent teeth and 514 million children suffer from caries of primary teeth. ",
    tooth : "Most oral health conditions are largely preventable and can be treated in their early stages. Most cases are dental caries (tooth decay), periodontal diseases, tooth loss and oral cancers. Other oral conditions of public health importance are orofacial clefts, noma (severe gangrenous disease starting in the mouth mostly affecting children) and oro-dental trauma. The WHO Global Oral Health Status Report (2022) estimated that oral diseases affect close to 3.5 billion people worldwide, with 3 out of 4 people affected living in middle-income countries. Globally, an estimated 2 billion people suffer from caries of permanent teeth and 514 million children suffer from caries of primary teeth. ",

    Ear : "The ear is one if the body’s most advanced and sensitive organs. When it is damaged or has been affected by something, it warns us that there is something wrong with our auditory system. the difficulty to hear due to partial, unilateral, bilateral or total hearing loss. It may be hereditary or the consequence of an illness, traumatism, long-term exposure to noise or aggressive medication for the auditory nerve.",
    ear : "The ear is one if the body’s most advanced and sensitive organs. When it is damaged or has been affected by something, it warns us that there is something wrong with our auditory system. the difficulty to hear due to partial, unilateral, bilateral or total hearing loss. It may be hereditary or the consequence of an illness, traumatism, long-term exposure to noise or aggressive medication for the auditory nerve.",

    Hair : "Both men and women develop this type of hair loss, which is the most common cause of hair loss worldwide. In men, it’s called male pattern hair loss. Women get female pattern hair loss. Regardless of whether it develops in a man or women, the medical term is androgenic alopecia. No matter which term you use, it means that you’ve inherited genes that cause your hair follicles (what each hair grows out of) to shrink and eventually stop growing hair. Shrinking can begin as early as your teens, but it usually starts later in life. In women, the first noticeable sign of hereditary hair loss is usually overall thinning or a widening part. When a man has hereditary hair loss, the first sign is often a receding hairline or bald spot at the top of his head.",

    "Blood Pressure" : "Blood pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood vessels in the body. Hypertension is when blood pressure is too high. Certain health conditions, such as diabetes and having obesity, can also increase the risk for developing high blood pressure. High blood pressure can also happen during pregnancy. You can manage your blood pressure to lower your risk for serious health problems that may affect your heart, brain, kidneys, and eyes.",
    "blood Pressure" : "Blood pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood vessels in the body. Hypertension is when blood pressure is too high. Certain health conditions, such as diabetes and having obesity, can also increase the risk for developing high blood pressure. High blood pressure can also happen during pregnancy. You can manage your blood pressure to lower your risk for serious health problems that may affect your heart, brain, kidneys, and eyes.",
    "blood pressure" : "Blood pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood vessels in the body. Hypertension is when blood pressure is too high. Certain health conditions, such as diabetes and having obesity, can also increase the risk for developing high blood pressure. High blood pressure can also happen during pregnancy. You can manage your blood pressure to lower your risk for serious health problems that may affect your heart, brain, kidneys, and eyes.",
    "Blood pressure" : "Blood pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood vessels in the body. Hypertension is when blood pressure is too high. Certain health conditions, such as diabetes and having obesity, can also increase the risk for developing high blood pressure. High blood pressure can also happen during pregnancy. You can manage your blood pressure to lower your risk for serious health problems that may affect your heart, brain, kidneys, and eyes.",
    "Hypertension" : "Blood pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood vessels in the body. Hypertension is when blood pressure is too high. Certain health conditions, such as diabetes and having obesity, can also increase the risk for developing high blood pressure. High blood pressure can also happen during pregnancy. You can manage your blood pressure to lower your risk for serious health problems that may affect your heart, brain, kidneys, and eyes.",
    "hypertension" : "Blood pressure is the force exerted by circulating blood against the walls of the body’s arteries, the major blood vessels in the body. Hypertension is when blood pressure is too high. Certain health conditions, such as diabetes and having obesity, can also increase the risk for developing high blood pressure. High blood pressure can also happen during pregnancy. You can manage your blood pressure to lower your risk for serious health problems that may affect your heart, brain, kidneys, and eyes.",
}

const fetchResponse = (userInput) => {
    return new Promise((res, reject) => {
        try {
            setTimeout(() => {
                res(responseObj[userInput]);
            }, 1200);
            // res(responseObj[userInput]);
        } catch (error) {
            reject(error);
        }
    });
    // return responseObj[userInput];
};

const chatBotService = {
    getBotResponse(userInput) {
        return fetchResponse(userInput);
    },
};

export default chatBotService;